import type { Metadata } from "next"
import { Host_Grotesk } from "next/font/google"
import { cookies } from "next/headers"
import { NextIntlClientProvider } from "next-intl"
import "./globals.css"
import { DEFAULT_LOCALE, getLocaleDir, isAppLocale } from "@/lib/i18n"
import OfflineBanner from "@/components/OfflineBanner"

// Host Grotesk font configuration
const hostGrotesk = Host_Grotesk({
  variable: "--font-host-grotesk",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
})

export const metadata: Metadata = {
  title: {
    default: "Gloord",
    template: "%s | Gloord",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/MVEX5UnwLzOpQMdE9hm9BVuMLIw.png",
    apple: "/apple-touch-icon.png",
  },
}

async function getMessages(locale: string) {
  return (await import(`../messages/${locale}.json`)).default
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const cookieLocale = cookieStore.get("NEXT_LOCALE")?.value
  const locale = isAppLocale(cookieLocale) ? cookieLocale : DEFAULT_LOCALE
  const messages = await getMessages(locale)

  return (
    <html
      lang={locale}
      dir={getLocaleDir(locale)}
      className={`${hostGrotesk.variable} bg-white text-tet`}
    >
      <body className="antialiased overflow-x-hidden">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <OfflineBanner />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}