import type { DoctorRecord, NewDoctorInput } from "@/lib/data-mappers"

export interface PatientRecord {
  id: string
  name: string
  email: string
  phone: string
  age: number
  gender: string
  concern: string
  totalCases: number
  approved: number
  pending: number
  rejected: number
  lastVisit: string
  status: "active" | "inactive"
  image: string
}

export const patientsSeed: PatientRecord[] = [
  {
    id: "P-45123",
    name: "Sarah Johnson",
    email: "sarah.j@mail.com",
    phone: "+1 (555) 123-4567",
    age: 28,
    gender: "Female",
    concern: "Eczema",
    totalCases: 3,
    approved: 2,
    pending: 1,
    rejected: 0,
    lastVisit: "Jan 24, 2026",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "P-45124",
    name: "Michael Chen",
    email: "michael.c@mail.com",
    phone: "+1 (555) 234-5678",
    age: 45,
    gender: "Male",
    concern: "Psoriasis",
    totalCases: 7,
    approved: 5,
    pending: 1,
    rejected: 1,
    lastVisit: "Feb 15, 2026",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "P-45125",
    name: "Emily Rodriguez",
    email: "emily.r@mail.com",
    phone: "+1 (555) 345-6789",
    age: 32,
    gender: "Female",
    concern: "Acne scarring",
    totalCases: 2,
    approved: 1,
    pending: 0,
    rejected: 1,
    lastVisit: "Mar 02, 2026",
    status: "inactive",
    image: "/images/patientimage.png",
  },
  {
    id: "P-45126",
    name: "James Wilson",
    email: "james.w@mail.com",
    phone: "+1 (555) 456-7890",
    age: 61,
    gender: "Male",
    concern: "Skin cancer screening",
    totalCases: 12,
    approved: 9,
    pending: 2,
    rejected: 1,
    lastVisit: "Dec 18, 2025",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "P-45127",
    name: "Maria Garcia",
    email: "maria.g@mail.com",
    phone: "+1 (555) 567-8901",
    age: 29,
    gender: "Female",
    concern: "Rosacea",
    totalCases: 1,
    approved: 1,
    pending: 0,
    rejected: 0,
    lastVisit: "Mar 10, 2026",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "P-45128",
    name: "Robert Smith",
    email: "robert.s@mail.com",
    phone: "+1 (555) 678-9012",
    age: 52,
    gender: "Male",
    concern: "Dermatitis",
    totalCases: 5,
    approved: 3,
    pending: 1,
    rejected: 1,
    lastVisit: "Feb 28, 2026",
    status: "inactive",
    image: "/images/patientimage.png",
  },
  {
    id: "P-45129",
    name: "Jennifer Lee",
    email: "jennifer.l@mail.com",
    phone: "+1 (555) 789-0123",
    age: 35,
    gender: "Female",
    concern: "Hyperpigmentation",
    totalCases: 4,
    approved: 3,
    pending: 1,
    rejected: 0,
    lastVisit: "Jan 05, 2026",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "P-45130",
    name: "David Brown",
    email: "david.b@mail.com",
    phone: "+1 (555) 890-1234",
    age: 41,
    gender: "Male",
    concern: "Melanoma follow-up",
    totalCases: 8,
    approved: 6,
    pending: 1,
    rejected: 1,
    lastVisit: "Nov 12, 2025",
    status: "inactive",
    image: "/images/patientimage.png",
  },
  {
    id: "P-45131",
    name: "Lisa Anderson",
    email: "lisa.a@mail.com",
    phone: "+1 (555) 901-2345",
    age: 27,
    gender: "Female",
    concern: "Acne vulgaris",
    totalCases: 2,
    approved: 1,
    pending: 1,
    rejected: 0,
    lastVisit: "Mar 18, 2026",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "P-45132",
    name: "Thomas Martinez",
    email: "thomas.m@mail.com",
    phone: "+1 (555) 012-3456",
    age: 38,
    gender: "Male",
    concern: "Contact dermatitis",
    totalCases: 6,
    approved: 4,
    pending: 1,
    rejected: 1,
    lastVisit: "Feb 03, 2026",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "P-45133",
    name: "Patricia Taylor",
    email: "patricia.t@mail.com",
    phone: "+1 (555) 112-4567",
    age: 57,
    gender: "Female",
    concern: "Skin tags",
    totalCases: 15,
    approved: 11,
    pending: 2,
    rejected: 2,
    lastVisit: "Oct 30, 2025",
    status: "inactive",
    image: "/images/patientimage.png",
  },
  {
    id: "P-45134",
    name: "Kevin White",
    email: "kevin.w@mail.com",
    phone: "+1 (555) 223-5678",
    age: 33,
    gender: "Male",
    concern: "Fungal infection",
    totalCases: 3,
    approved: 2,
    pending: 1,
    rejected: 0,
    lastVisit: "Mar 22, 2026",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "P-45135",
    name: "Nancy Moore",
    email: "nancy.m@mail.com",
    phone: "+1 (555) 334-6789",
    age: 49,
    gender: "Female",
    concern: "Melasma",
    totalCases: 9,
    approved: 7,
    pending: 1,
    rejected: 1,
    lastVisit: "Dec 05, 2025",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "P-45136",
    name: "Daniel Jackson",
    email: "daniel.j@mail.com",
    phone: "+1 (555) 445-7890",
    age: 44,
    gender: "Male",
    concern: "Vitiligo",
    totalCases: 11,
    approved: 8,
    pending: 2,
    rejected: 1,
    lastVisit: "Jan 19, 2026",
    status: "inactive",
    image: "/images/patientimage.png",
  },
  {
    id: "P-45137",
    name: "Michelle Thompson",
    email: "michelle.t@mail.com",
    phone: "+1 (555) 556-8901",
    age: 31,
    gender: "Female",
    concern: "Sun damage",
    totalCases: 4,
    approved: 3,
    pending: 1,
    rejected: 0,
    lastVisit: "Feb 21, 2026",
    status: "active",
    image: "/images/patientimage.png",
  },
]

export const doctorsSeed: DoctorRecord[] = [
  {
    id: "D003",
    name: "Sarah Johnson",
    email: "sarah.johnson@clinic.com",
    phone: "+1 (555) 201-3344",
    specialty: "Dermatology",
    approved: 42,
    pending: 5,
    rejected: 3,
    totalCases: 50,
    lastActive: "Jan 24, 2026",
    experience: 12,
    license: "MD-29384",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "D004",
    name: "Michael Chen",
    email: "michael.chen@clinic.com",
    phone: "+1 (555) 302-7781",
    specialty: "Cosmetic Dermatology",
    approved: 38,
    pending: 7,
    rejected: 2,
    totalCases: 47,
    lastActive: "Feb 15, 2026",
    experience: 8,
    license: "MD-44102",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "D005",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@clinic.com",
    phone: "+1 (555) 410-9953",
    specialty: "Pediatric Dermatology",
    approved: 25,
    pending: 4,
    rejected: 3,
    totalCases: 32,
    lastActive: "Mar 02, 2026",
    experience: 6,
    license: "MD-55210",
    status: "inactive",
    image: "/images/patientimage.png",
  },
  {
    id: "D006",
    name: "James Wilson",
    email: "james.wilson@clinic.com",
    phone: "+1 (555) 519-6620",
    specialty: "Dermatopathology",
    approved: 55,
    pending: 3,
    rejected: 3,
    totalCases: 61,
    lastActive: "Dec 18, 2025",
    experience: 18,
    license: "MD-11093",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "D007",
    name: "Maria Garcia",
    email: "maria.garcia@clinic.com",
    phone: "+1 (555) 607-2218",
    specialty: "Dermatology",
    approved: 20,
    pending: 8,
    rejected: 1,
    totalCases: 29,
    lastActive: "Mar 10, 2026",
    experience: 4,
    license: "MD-67344",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "D008",
    name: "Robert Smith",
    email: "robert.smith@clinic.com",
    phone: "+1 (555) 715-8890",
    specialty: "Mohs Surgery",
    approved: 44,
    pending: 2,
    rejected: 6,
    totalCases: 52,
    lastActive: "Feb 28, 2026",
    experience: 15,
    license: "MD-22019",
    status: "inactive",
    image: "/images/patientimage.png",
  },
  {
    id: "D009",
    name: "Jennifer Lee",
    email: "jennifer.lee@clinic.com",
    phone: "+1 (555) 812-1147",
    specialty: "Dermatology",
    approved: 30,
    pending: 3,
    rejected: 2,
    totalCases: 35,
    lastActive: "Jan 05, 2026",
    experience: 9,
    license: "MD-39401",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "D010",
    name: "David Brown",
    email: "david.brown@clinic.com",
    phone: "+1 (555) 923-5504",
    specialty: "Cosmetic Dermatology",
    approved: 34,
    pending: 4,
    rejected: 3,
    totalCases: 41,
    lastActive: "Nov 12, 2025",
    experience: 11,
    license: "MD-48837",
    status: "inactive",
    image: "/images/patientimage.png",
  },
  {
    id: "D011",
    name: "Lisa Anderson",
    email: "lisa.anderson@clinic.com",
    phone: "+1 (555) 104-6692",
    specialty: "Dermatology",
    approved: 22,
    pending: 3,
    rejected: 2,
    totalCases: 27,
    lastActive: "Mar 18, 2026",
    experience: 5,
    license: "MD-71560",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "D012",
    name: "Thomas Martinez",
    email: "thomas.martinez@clinic.com",
    phone: "+1 (555) 218-3340",
    specialty: "Immunodermatology",
    approved: 28,
    pending: 6,
    rejected: 4,
    totalCases: 38,
    lastActive: "Feb 03, 2026",
    experience: 10,
    license: "MD-82915",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "D013",
    name: "Patricia Taylor",
    email: "patricia.taylor@clinic.com",
    phone: "+1 (555) 329-1178",
    specialty: "Dermatopathology",
    approved: 49,
    pending: 2,
    rejected: 6,
    totalCases: 57,
    lastActive: "Oct 30, 2025",
    experience: 20,
    license: "MD-10287",
    status: "inactive",
    image: "/images/patientimage.png",
  },
  {
    id: "D014",
    name: "Kevin White",
    email: "kevin.white@clinic.com",
    phone: "+1 (555) 437-8826",
    specialty: "Dermatology",
    approved: 28,
    pending: 4,
    rejected: 1,
    totalCases: 33,
    lastActive: "Mar 22, 2026",
    experience: 7,
    license: "MD-93641",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "D015",
    name: "Nancy Moore",
    email: "nancy.moore@clinic.com",
    phone: "+1 (555) 546-2204",
    specialty: "Pediatric Dermatology",
    approved: 40,
    pending: 5,
    rejected: 4,
    totalCases: 49,
    lastActive: "Dec 05, 2025",
    experience: 14,
    license: "MD-05728",
    status: "active",
    image: "/images/patientimage.png",
  },
  {
    id: "D016",
    name: "Daniel Jackson",
    email: "daniel.jackson@clinic.com",
    phone: "+1 (555) 654-9961",
    specialty: "Mohs Surgery",
    approved: 36,
    pending: 3,
    rejected: 5,
    totalCases: 44,
    lastActive: "Jan 19, 2026",
    experience: 13,
    license: "MD-16470",
    status: "inactive",
    image: "/images/patientimage.png",
  },
  {
    id: "D017",
    name: "Michelle Thompson",
    email: "michelle.thompson@clinic.com",
    phone: "+1 (555) 763-7739",
    specialty: "Cosmetic Dermatology",
    approved: 26,
    pending: 3,
    rejected: 2,
    totalCases: 31,
    lastActive: "Feb 21, 2026",
    experience: 6,
    license: "MD-58193",
    status: "active",
    image: "/images/patientimage.png",
  },
]

export type AddDoctorInput = NewDoctorInput

